server:
  port: 8082
spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    url: jdbc:mysql://123.57.66.141:3306/mes_device
    username: root
    password: xiexie402
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis-plus:
  configuration:
    default-fetch-size: 512
    call-setters-on-nulls: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl